<?xml version="1.0" ?>
<!DOCTYPE Books [
  <!ELEMENT Books (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (Id?,AuthorId?,CategoryId?,CoverImage?,ISBN?,Name?,Page?,Publisher?,PublishingYear?)+>
  <!ELEMENT Id (#PCDATA)>
  <!ELEMENT AuthorId (#PCDATA)>
  <!ELEMENT CategoryId (#PCDATA)>
  <!ELEMENT CoverImage (#PCDATA)>
  <!ELEMENT ISBN (#PCDATA)>
  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Page (#PCDATA)>
  <!ELEMENT Publisher (#PCDATA)>
  <!ELEMENT PublishingYear (#PCDATA)>
]>
<Books>
  <DATA_RECORD>
    <Id>1</Id>
    <AuthorId>1</AuthorId>
    <CategoryId>1</CategoryId>
    <CoverImage>/opt/lib/practical_avon_loan.pot</CoverImage>
    <ISBN>4,951,433,321,004</ISBN>
    <Name>odit cum laudantium</Name>
    <Page>122</Page>
    <Publisher>nemo est odit</Publisher>
    <PublishingYear>1,959</PublishingYear>
  </DATA_RECORD>
</Books>
